# Generated by Django 2.0.1 on 2018-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatusRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='状态名')),
                ('step', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
