# Generated by Django 2.0.1 on 2018-05-23 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='请求')),
                ('request_header', models.TextField(verbose_name='请求头')),
                ('request', models.TextField(verbose_name='请求内容')),
                ('response_header', models.TextField(verbose_name='响应头')),
                ('response', models.TextField(verbose_name='响应内容')),
                ('actiontime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求时间')),
            ],
        ),
        migrations.CreateModel(
            name='ActionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='请求')),
                ('request', models.TextField(verbose_name='请求内容')),
                ('request_header', models.TextField(verbose_name='请求头')),
                ('response', models.TextField(verbose_name='响应内容')),
                ('response_header', models.TextField(verbose_name='响应头')),
                ('status_step', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
